name: Publish Site CI

on:
  push:
    branches:
      - master
      - publish

jobs:
  build-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: publish
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - name: build site
        run: yarn run docs:build
      - name: publish site
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f master:${PUBLISH_BRANCH:-gh-pages}
